### PR TITLE
Fixed errors & warnings

### PR DESCRIPTION
**Pull request by mathieustan**
- issue #28: Error: Meteor data 'subscribe' ...
- issue #29: 
	Cannot read property 'push' of null
	Property already used in the component data

### CODE REVIEW

**Comment by mathieustan** [comment]
@Akryum any idea ? Have you seen those issues ?

**Comment by mathieustan** [comment]
@Akryum what do you think about this PR ? Could we merge it ?

**Comment by moslemir** [comment]
@mathieustan @Akryum 
I think this project is dead.
Because it has not been updated yet.

**Comment by mathieustan** [comment]
@moslemir @Akryum I hope not. 
We really need this new version, because it solves issues with subReady reactivity which is really important for us.

**Comment by mathieustan** [comment]
@Akryum Do you mind to check this PR ?

**Pull request closed without merging**
